
CREATE TABLE book ( id INT NOT NULL AUTO_INCREMENT, title VARCHAR(45) NULL, author VARCHAR(45) NULL, PRIMARY KEY (id));
CREATE TABLE notebook ( id INT NOT NULL AUTO_INCREMENT, title VARCHAR(45) NULL, author VARCHAR(45) NULL, PRIMARY KEY (id));